layout_spectrum: 0.5595745
color:
  saturation: 0.3170213
  lightness: 0.5702128
  brandStrength: 0
  brandColors:
    - '#1F3002'
    - '#01016D'
    - '#E0BE01'
    - '#A40D01'
    - '#CEC6BD'
  rhythmicContrast: 0.4873755
typography_spectrum: 0.4893617
name: Www.tourgolftees.com
